theme: jekyll-theme-time-machine
# profile
## my story is ....
### my favorite flase
>> * Change your mind *
>> * keep your mind *
>> * I wear my pant *
Japanse comedian flase of  "*tonikaku akarui yasumura *" 
<br>
### my favorite food ..
is Apple Banana Orange etc..
<br>
MIX at all..
<br>
<imagewidth = "4050.px", alt = "読書と美女", src ="C:\Users\enPiT-P11\Downloads\読書と美女.jpg"> 
<br>
smuuze!!
<br>
### 最後に
### my hair is bad
is my favorite singer!
<br>
** FIN **
<br>
